#include "Temputer.h"

_TEMPIOS TEMPIOS = {
	.TEMP1={GPIOC,PIN13},
	.TEMP2={GPIOC,PIN14},
	.TEMP3={GPIOC,PIN15},
};

void LedsInit(void)
{
	TEMPSIOCLKEN;
	IoInit(TEMPIOS.TEMP1.PORT,TEMPIOS.TEMP1.PIN,IOIN,NOPU);
	IoInit(TEMPIOS.TEMP2.PORT,TEMPIOS.TEMP2.PIN,IOIN,NOPU);
	IoInit(TEMPIOS.TEMP3.PORT,TEMPIOS.TEMP3.PIN,IOIN,NOPU);
}
